//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInge1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cambio
    {
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public string Justificacion { get; set; }
        public string IdRequerimiento { get; set; }
        public string CedulaUsuario { get; set; }
        public string IdUsuario { get; set; }
    
        public virtual Requerimiento Requerimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
