//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInge1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriterioAceptacionHistorial
    {
        public string Escenario { get; set; }
        public string Descripcion { get; set; }
        public string IdRequerimiento { get; set; }
        public string IdProyecto { get; set; }
        public int IdSolicitud { get; set; }
        public Nullable<bool> Borrar { get; set; }
        public virtual Cambio Cambio { get; set; }
    }
}
