//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInge1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CriterioAceptacion
    {
        [RegularExpression(@"[0-9a-zA-Z\-_áéíóúñ\s]+", ErrorMessage = "Solo se pueden ingresar letras, números y guiones")]
        public string Escenario { get; set; }
        [Required(ErrorMessage = "La descripción es un campo requerido.")]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        public string IdRequerimiento { get; set; }
        public string IdProyecto { get; set; }
        public Nullable<bool> Borrar { get; set; }
    
        public virtual Requerimiento Requerimiento { get; set; }
    }
}
