//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoInge1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Requerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requerimiento()
        {
            this.Cambio = new HashSet<Cambio>();
            this.CriterioAceptacion = new HashSet<CriterioAceptacion>();
        }
    
        public string Id { get; set; }
        public string Nombre { get; set; }
        public string Prioridad { get; set; }
        public string Esfuerzo { get; set; }
        public string Estado { get; set; }
        [DataType(DataType.MultilineText)]
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public string Sprint { get; set; }
        public string Modulo { get; set; }
        [DataType(DataType.MultilineText)]
        public string Observaciones { get; set; }
        public string IdProyecto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cambio> Cambio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriterioAceptacion> CriterioAceptacion { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
